version: 0.2
phases:
  install:
    commands:
      - echo Installing app dependencies...
      - curl -o kubectl https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.16/2020-11-02/bin/linux/amd64/kubectl
      - chmod +x ./kubectl
      - mkdir -p $HOME/bin && mv ./kubectl $HOME/bin/kubectl && export PATH=$PATH:$HOME/bin
  pre_build:
    commands:
      - REGION=eu-central-1
      - aws --version
      - echo $CODEBUILD_SOURCE_VERSION
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $REGION | docker login --username AWS --password-stdin 062033262036.dkr.ecr.eu-central-1.amazonaws.com
      - echo Logging in to Amazon EKS...
      - aws eks --region $REGION update-kubeconfig --name baykar-test-env
      - REPOSITORY_URI_API_SERVER=062033262036.dkr.ecr.eu-central-1.amazonaws.com/api-server
      - REPOSITORY_URI_REACT_APP=062033262036.dkr.ecr.eu-central-1.amazonaws.com/react-app
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
      - kubectl version
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...         
      - docker build --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI --build-arg AWS_REGION=$REGION -t $REPOSITORY_URI_API_SERVER:latest -f ./server/Dockerfile ./server/
      - docker build --build-arg AWS_CONTAINER_CREDENTIALS_RELATIVE_URI=$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI --build-arg AWS_REGION=$REGION -t $REPOSITORY_URI_REACT_APP:latest -f ./client/Dockerfile ./client/
      - echo Build completed.
  post_build:
    commands:
      - echo Pushing the Docker images...
      - NEW_IMAGE_API_SERVER=$REPOSITORY_URI_API_SERVER:master-$IMAGE_TAG
      - docker tag $REPOSITORY_URI_API_SERVER:latest $NEW_IMAGE_API_SERVER
      - docker push $NEW_IMAGE_API_SERVER
      - NEW_IMAGE_REACT_APP=$REPOSITORY_URI_REACT_APP:master-$IMAGE_TAG
      - docker tag $REPOSITORY_URI_REACT_APP:latest $NEW_IMAGE_REACT_APP
      - docker push $NEW_IMAGE_REACT_APP
      - echo Modifying manifests...
      - echo Run deployment...
      - kubectl apply -f deployment-files/react-app.yml
      - kubectl apply -f deployment-files/api-server.yml
      - kubectl apply -f deployment-files/mongo.yml
      - echo All success!
